---
AWSTemplateFormatVersion: '2010-09-09'
#Transform: 'AWS::Serverless-2016-10-31'  # This template is currently plain CloudFormation - no SAM

Description: >-
  ML Project template for running in the frugal-MLOps demo environment.

Parameters:
  ProjectId:
    Description: Used as a prefix for project resources.  3-15 characters, lowercase letters (a-z) only.
    Type: String
    Default: forestcover
    AllowedPattern: "^[a-z]{3,15}"
    ConstraintDescription: The ProjectId can be 3-15 characters, lowercase letters (a-z) only.

  StudioUserName:
    Description: User profile name in SageMaker Studio of the data scientist to add to the project.
    Type: String

  ForceRefreshToken:
    Description: >-
      Optional token parameter to force this stack's descriptive resources (e.g. pointer to existing SMStudio
      domain) to update, to consume changes applied externally.
    Type: Number
    Default: 0

Resources:

  # Details of the existing SMStudio user:
  UserProfileDetails:
    Type: 'Custom::ExistingSageMakerStudioUserProfile'
    Properties:
      ServiceToken: !Sub '{{resolve:ssm:/MLEnvSetup/CFnDescribeUserProfileLambdaArn:1}}'
      UserProfileName: !Ref StudioUserName
      ForceRefreshToken: !Ref ForceRefreshToken

  # Main sandbox bucket to use for experimentation:
  PersonalSandboxBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Use join to drop forbidden IAM Role name characters for bucket name:
      # Too long with default example user role name
      #BucketName: !Join ['-', [!Ref ProjectId, 'sandbox', !Join ['-', !Split ['+', !Join ['-', !Split ['=', !Join ['-', !Split [',', !Join ['-', !Split ['@', !Join ['-', !Split ['_', !Ref UserExecutionRole]]]]]]]]]] ]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  # Store generated bucket name in SSM for notebooks to retrieve the location:
  PersonalSandboxBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub 'ID of personal artifacts bucket for ${UserProfileDetails.ExecutionRoleName}'
      Name: !Sub '/MLEnv/Projects/${ProjectId}/${UserProfileDetails.ExecutionRoleName}/SandboxBucket'
      Type: String
      Value: !Ref PersonalSandboxBucket

  # Additional sandbox bucket for more persistent artifacts:
  PersonalArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Use join to drop forbidden IAM Role name characters for bucket name:
      # Too long with default example user role name
      #BucketName: !Join ['-', [!Ref ProjectId, 'artifacts', !Join ['-', !Split ['+', !Join ['-', !Split ['=', !Join ['-', !Split [',', !Join ['-', !Split ['@', !Join ['-', !Split ['_', !Ref UserExecutionRole]]]]]]]]]] ]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  # Store generated bucket name in SSM for notebooks to retrieve the location:
  PersonalArtifactsBucketParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Sub 'ID of personal artifacts bucket for ${UserProfileDetails.ExecutionRoleName}'
      Name: !Sub '/MLEnv/Projects/${ProjectId}/${UserProfileDetails.ExecutionRoleName}/ArtifactsBucket'
      Type: String
      Value: !Ref PersonalArtifactsBucket

  # Policy for access to personal (sandbox) resources
  PersonalAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${ProjectId}-${UserProfileDetails.ExecutionRoleName}-prs'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: !Sub 'PersonalBucketsAccess'
            Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !GetAtt PersonalArtifactsBucket.Arn
              - !Sub '${PersonalArtifactsBucket.Arn}/*'
              - !GetAtt PersonalSandboxBucket.Arn
              - !Sub '${PersonalSandboxBucket.Arn}/*'
      Roles:
        - !GetAtt UserProfileDetails.ExecutionRoleName

  ProjectPolicyAttachment:
    Type: 'Custom::UserPermissions'
    Properties:
      ServiceToken: !Sub '{{resolve:ssm:/MLEnvSetup/CFnPolicyAttachmentLambdaArn:1}}'
      Users:
        - !Ref StudioUserName
      PolicyArn: !Sub '{{resolve:ssm:/MLEnv/Projects/${ProjectId}/DataSciencePolicyArn:1}}'

Outputs:
  PersonalSandboxBucket:
    Value: !Ref PersonalSandboxBucket
    Description: Main sandbox bucket to use for experimentation
  PersonalArtifactsBucket:
    Value: !Ref PersonalArtifactsBucket
    Description: Additional sandbox bucket for more persistent artifacts
